### ISSUE TITLE
`--fix` options not working?

### ISSUE THREAD

**Issue by cheerfyt** [duaraghav8/Solium#125]
When i do:

```bash
$ solium -f contracts/ConvertLib.sol --fix
```

I get:

```bash
In contracts/ConvertLib.sol, line 3:
library ConvertLib {
^-- WARNING: LibraryStatement 'ConvertLib' must be preceded by a 2-line gap.

No fixes were applied.
1 warning found.
```
```bash
$ solium --version
0.5.5
```

So why the warning not be fixed? 

Thanks
cheerfyt

**Comment by duaraghav8** [comment]
@cheerfyt the option works as expected.

Fixes for all possible errors have not been implemented yet. Whichever rules have the fix mechanism (for eg- the `quotes` rule does) will apply it. More fixes will be added in future, you can see the [list of rules](http://solium.readthedocs.io/en/latest/user-guide.html#list-of-core-rules) to know which ones are currently able to apply fixes.

So if you see a warning/error, its because that issue wasn't patched by `--fix`.

I should probably clarify this in the docs as well, thanks for reporting.

**Comment by duaraghav8** [comment]
closing this issue since it doesn't seem to be a problem.
