### ISSUE TITLE
Make solium less opinionated by default as far as styling is concerned.

### ISSUE THREAD

**Issue by LefterisJP** [duaraghav8/Solium#159]
Hey,

I recently integrated solium to emacs solidity mode. It's great but also rather opinionated. It follows a particular style whoever wrote solidity's read the docs liked (camelcase) and makes anything else appear as errors or warnings. 

I know that these can be configured and turned off but it would be better if the user could avoid style suggestions unless requested. I find it annoying to have to disable all style rules. And for my styling rules there is no enforcement. For example I can't enforce snake case.

Examples of opinionated errors:

```
 warning    FunctionDeclaration must be succeeded by 1 blank line
error      Opening brace must be on a new line immediately after the last modifier.
 error      Opening brace must be on the line after returns declaration
```

And the last 2 should only have been warnings. There is no error involved. It's a style choice to have the brace like that, and a rather popular one called [K&R](https://en.wikipedia.org/wiki/Indentation_style#K&R).

Also this warning is rather off:

```
 warning    Function "ecrecover": in case of more than 3 arguments, drop each into its own line.
```
It is not the number of arguments that count but the number of columns they take. Most projects I have worked in always keep arguments in one line, unless the function call exceeds the XX column limit (with XX being either 80 or 100) in which case yes indeed each argument is split into its own line.

I suggest having style choices grouped into something like the different indentation styles seen [here](https://en.wikipedia.org/wiki/Indentation_style) and allow the user to choose one and then fine-tune through specific options. But not only support the camelcase style that is supported now.

If you want to have a style linter make it one that can be used by all groups, not only one particular style.

**Comment by duaraghav8** [comment]
Agreed, I believe the solidity style guide's rules are more suited as an optional ruleset (the current default ruleset is `solium:all` that you see in your `.soliumrc.json` which basically applies all the rules).

IMO here is how we can improve the linter:
- Add rules for all the different types of styles (snake, camel, etc) - all disabled by default.
- Allow user to enable/disable rules based on their own styles
- Because the 2nd step can be annoying depending on how much customization you need to do, solium can provide some other rulesets (eg- `solium:style-guide`, `solium:knr-gnu`, etc or [sharable configs](http://solium.readthedocs.io/en/latest/user-guide.html#sharable-configs) for that matter) that one can switch to.
- The default ruleset applied when running `solium --init` will be `solium:recommended` - this itself would contain only a small no. of style rules which would generally apply to all solidity code (so wouldn't complain about your variable naming style for example)

Feel free to give your input on this^, thanks for the detailed feedback!

**Comment by duaraghav8** [comment]
v1.1.3 introduces the `solium:recommended` ruleset - https://github.com/duaraghav8/Solium/blob/master/config/rulesets/solium-recommended.js.

Would love to hear you out in case you have more feedback.
