### ISSUE TITLE
[Feature request] Add "dynamic" option for the rule "linebreak-style"

### ISSUE THREAD

**Issue by jackycjh** [duaraghav8/Solium#237]
## Problem encountered

While using a VS Code extension `juanblanco.solidity` (repository: https://github.com/juanfranblanco/vscode-solidity) on a Windows platform, the default rule of `linebreak-style` is unable to determine the OS platform it's running on, when the extension runs the Solium linter.

### Reference

More info at: https://github.com/juanfranblanco/vscode-solidity/issues/86

## Ideal feature/improvement

According to implementation in https://github.com/duaraghav8/Solium/blob/master/lib/rules/linebreak-style.js
Ideally add another option string "dynamic" and detect the OS platform using `process.platform` to determine whether the linebreak style should be `LF` or `CRLF`?

**_Disclaimer:_** _I'm not a JS expert, reference found from https://stackoverflow.com/a/8684009/4003061_

**Comment by duaraghav8** [comment]
@jackycjh Actually this rule (or the whole of Solium) doesn't require the `dynamic` option. Ideally, Solium's rules should detect the platform and modify their behaviour.
There are currently bugs in Solium (related to linebreak style) causing it to be incompatible with Windows at the moment. I'd highly recommend you use Solium in a Unix or Darwin environment for now. These bugs are going to take some time to get fixed, since they're all part of legacy code.

**Comment by jackycjh** [comment]
Noted, thanks for the explanation.

Will look forward for getting Solium works nicely in Windows, hopefully also works in the ideal fashion that it could detect and modify the rule preferences.

**Comment by duaraghav8** [comment]
Please feel free to re-open the issue in case you face any other related problem :)
